apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-deployment
  namespace: techtrends
  labels:
    app: techtrends
spec:
  replicas: 4
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: hosamelbasiony/techtrends-udacity-k8s:v1.0.0
        ports:
        - containerPort: 80
        env:
        - name: techtrends_DB_HOST
          valueFrom:
            secretKeyRef:
              name: techtrends
              key: techtrends_DB_HOST
        - name: techtrends_DB_USER
          valueFrom:
            secretKeyRef:
              name: techtrends
              key: techtrends_DB_USER
        - name: techtrends_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: techtrends
              key: techtrends_DB_PASSWORD
        - name: techtrends_DB_NAME
          valueFrom:
            secretKeyRef:
              name: techtrends
              key: techtrends_DB_NAME